server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
zuul:
  routes:
      myUser.serviceId: SERVICE-PROVIDER
      myUser.path: /myUser/**       #代表了path对应的路径匹配此服务
  ignored-services: "*"
  prefix: "/provider"   #这是所有路径的前缀